import type { Event, EventType, EventCreator } from '@/components/types'

export const eventCreatorsList: EventCreator[] = [
  {
    id: 'user1',
    fullName: 'Jack Black',
  },
  {
    id: 'user2',
    fullName: 'Bob Dylan',
  },
  {
    id: 'user3',
    fullName: 'Tina Turner',
  },
  {
    id: 'user4',
    fullName: 'Ben Kingsley',
  },
  {
    id: 'user5',
    fullName: 'Samuel L. Jackson',
  },
]

export const eventTypesList: EventType[] = [
  {
    id: 'eventType1',
    name: 'Music Concert',
    ulid: 'eventType1',
  },
  {
    id: 'eventType2',
    name: 'Festival & Culture',
    ulid: 'eventType2',
  },
  {
    id: 'eventType3',
    name: 'Sporting Event',
    ulid: 'eventType3',
  },
  {
    id: 'eventType4',
    name: 'Political Event',
    ulid: 'eventType4',
  },
  {
    id: 'eventType5',
    name: 'Business Conference',
    ulid: 'eventType5',
  },
]

export const eventsList: Event[] = [
  {
    ulid: 'event1',
    userId: eventCreatorsList[2].id,
    title: 'Wimbledon Men’s Singles Final',
    content: '<h1>Wimbledon Men’s Singles Final</h1><p>Five sets of pure drama under the roof on Centre Court.</p><p>It was decided by a tie break in the gathering dusk.</p>',
    contentPlain: 'Wimbledon Men’s Singles Final\n\nFive sets of pure drama under the roof on Centre Court.\n\nIt was decided by a tie break in the gathering dusk.',
    eventDate: new Date(2026, 6, 12),
    rating: 'great',
    authorName: eventCreatorsList[2].fullName,
    eventTypes: [eventTypesList[2]],
    createdAt: new Date(2026, 6, 13),
    updatedAt: new Date(2026, 6, 14),
  },
  {
    ulid: 'event2',
    userId: eventCreatorsList[1].id,
    title: 'Tech Startup Funding Announcement',
    content: '<h1>Tech Startup Funding</h1><p>Shoreditch, 5th February. A local fintech raised a record round and pledged to double headcount.</p>',
    contentPlain: 'Tech Startup Funding\nShoreditch, 5th February.  A local fintech raised a record round and pledged to double headcount.',
    eventDate: new Date(2026, 1, 5),
    rating: 'good',
    authorName: eventCreatorsList[1].fullName,
    eventTypes: [eventTypesList[4]],
    createdAt: new Date(2026, 1, 6),
    updatedAt: new Date(2026, 1, 8),
  },
  {
    ulid: 'event3',
    userId: eventCreatorsList[2].id,
    title: 'Notting Hill Carnival',
    content: '<h1>Notting Hill Carnival</h1><p>Feathers, steel drums and the smell of jerk chicken filled West London.</p><p>The parade took the best part of an afternoon to pass one corner.</p>',
    contentPlain: 'Notting Hill Carnival\nFeathers, steel drums and the smell of jerk chicken filled West London.\nThe parade took the best part of an afternoon to pass one corner.',
    eventDate: new Date(2026, 7, 31),
    rating: 'great',
    authorName: eventCreatorsList[2].fullName,
    eventTypes: [eventTypesList[1]],
    createdAt: new Date(2026, 7, 10),
    updatedAt: new Date(2026, 8, 1),
  },
  {
    ulid: 'event4',
    userId: eventCreatorsList[4].id,
    title: 'Prime Minister’s Questions',
    content: '<h1>Prime Minister’s Questions</h1><p><em>18th June, the Commons.</em></p><p>Temperatures rose as the benches traded barbs over the cost of living.</p>',
    contentPlain: 'Prime Minister’s Questions\n18th June, the Commons.\nTemperatures rose as the benches traded barbs over the cost of living.',
    eventDate: new Date(2026, 5, 18),
    rating: 'bad',
    authorName: eventCreatorsList[4].fullName,
    eventTypes: [eventTypesList[3]],
    createdAt: new Date(2026, 5, 18),
    updatedAt: new Date(2026, 5, 19),
  },
  {
    ulid: 'event5',
    userId: eventCreatorsList[2].id,
    title: 'Taylor Swift - The Eras Tour',
    content: '<h2>The Eras Tour</h2><p>Three hours, ten eras, one very long night at the O2 Arena.</p><p>The surprise acoustic section caught everyone off guard.</p>',
    contentPlain: 'The Eras Tour\n\nThree hours, ten eras, one very long night at the O2 Arena.\n\nThe surprise acoustic section caught everyone off guard.',
    eventDate: new Date(2026, 11, 3),
    rating: 'great',
    authorName: eventCreatorsList[2].fullName,
    eventTypes: [eventTypesList[0]],
    createdAt: new Date(2026, 5, 1),
    updatedAt: new Date(2026, 5, 20),
  },
  {
    ulid: 'event6',
    userId: eventCreatorsList[4].id,
    title: 'Retail Supply Chain Summit',
    content: '<h1>Retail Supply Chain Summit</h1><p>NEC, 9th October. Logistics leaders met to discuss resilience after a turbulent year.</p><p><em>Shipping delays and rising costs dominated the agenda.</em></p>',
    contentPlain: 'Retail Supply Chain Summit\nNEC, 9th October.  Logistics leaders met to discuss resilience after a turbulent year.\nShipping delays and rising costs dominated the agenda.',
    eventDate: new Date(2026, 9, 9),
    rating: 'none',
    authorName: eventCreatorsList[4].fullName,
    eventTypes: [eventTypesList[4]],
    createdAt: new Date(2026, 9, 10),
    updatedAt: new Date(2026, 9, 12),
  },
  {
    ulid: 'event7',
    userId: eventCreatorsList[0].id,
    title: 'The Ashes, Fifth Test',
    content: '<h1>The Ashes, Fifth Test</h1><p><em>The Oval, 28th July.</em></p><p>A tense final day ended in a draw that felt like a victory.</p>',
    contentPlain: 'The Ashes, Fifth Test\nThe Oval, 28th July.\nA tense final day ended in a draw that felt like a victory.',
    eventDate: new Date(2026, 6, 28),
    rating: 'neutral',
    authorName: eventCreatorsList[0].fullName,
    eventTypes: [eventTypesList[2]],
    createdAt: new Date(2026, 6, 29),
    updatedAt: new Date(2026, 7, 2),
  },
  {
    ulid: 'event8',
    userId: eventCreatorsList[3].id,
    title: 'Diwali in Leicester',
    content: '<h1>Diwali in Leicester</h1><ul><li>Thousands of lights on the Golden Mile</li><li>Fireworks above Belgrave Road</li><li>Sweet stalls on every corner</li></ul>',
    contentPlain: 'Diwali in Leicester\n* Thousands of lights on the Golden Mile\n* Fireworks above Belgrave Road\n* Sweet stalls on every corner',
    eventDate: new Date(2026, 10, 8),
    rating: 'great',
    authorName: eventCreatorsList[3].fullName,
    eventTypes: [eventTypesList[1]],
    createdAt: new Date(2026, 9, 20),
    updatedAt: new Date(2026, 10, 9),
  },
  {
    ulid: 'event9',
    userId: eventCreatorsList[0].id,
    title: 'Michael Jackson - Bad',
    content: '<h1>5th November at the Wolverhampton Civic Hall</h1><br /><p>He\'s back and badder than ever before.  Singing all his greatest hits and dancing a lot on stage. When the wheels are turning the rock starts poppin!</p>',
    contentPlain: '5th November at the Wolverhampton Civic Hall\nHe\'s back and badder than ever before.  Singing all his greatest hits and dancing a lot on stage.  When the wheels are turning the rock starts poppin!',
    eventDate: new Date(2026, 10, 5),
    rating: 'good',
    authorName: eventCreatorsList[0].fullName,
    eventTypes: [eventTypesList[0]],
    createdAt: new Date(2026, 4, 27),
    updatedAt: new Date(2026, 5, 15),
  },
  {
    ulid: 'event10',
    userId: eventCreatorsList[2].id,
    title: 'Budget Day in Westminster',
    content: '<h2>Budget Day</h2><p>Westminster, 11th March.</p><p>Protesters and press gathered as the Chancellor delivered the statement.</p><p>Reactions varied wildly across the crowd.</p>',
    contentPlain: 'Budget Day\nWestminster, 11th March.\nProtesters and press gathered as the Chancellor delivered the statement.\nReactions varied wildly across the crowd.',
    eventDate: new Date(2026, 2, 11),
    rating: 'bad',
    authorName: eventCreatorsList[2].fullName,
    eventTypes: [eventTypesList[3]],
    createdAt: new Date(2026, 2, 11),
    updatedAt: new Date(2026, 2, 12),
  },
  {
    ulid: 'event11',
    userId: eventCreatorsList[3].id,
    title: 'Green Energy Investment Forum',
    content: '<h2>Green Energy Investment Forum</h2><ul><li>Offshore wind panels</li><li>Battery storage debate</li><li>Renewed investor appetite</li></ul>',
    contentPlain: 'Green Energy Investment Forum\n* Offshore wind panels\n* Battery storage debate\n* Renewed investor appetite',
    eventDate: new Date(2026, 3, 22),
    rating: 'good',
    authorName: eventCreatorsList[3].fullName,
    eventTypes: [eventTypesList[4]],
    createdAt: new Date(2026, 3, 23),
    updatedAt: new Date(2026, 3, 25),
  },
  {
    ulid: 'event12',
    userId: eventCreatorsList[4].id,
    title: 'Beyoncé - Renaissance World Tour',
    content: '<h1>Renaissance World Tour</h1><p><strong>Tottenham Hotspur Stadium, 18th July.</strong></p><p>A dazzling display of choreography, vocals and one giant disco ball.</p>',
    contentPlain: 'Renaissance World Tour\nTottenham Hotspur Stadium, 18th July.\nA dazzling display of choreography, vocals and one giant disco ball.',
    eventDate: new Date(2026, 6, 18),
    rating: 'great',
    authorName: eventCreatorsList[4].fullName,
    eventTypes: [eventTypesList[0]],
    createdAt: new Date(2026, 2, 9),
    updatedAt: new Date(2026, 3, 1),
  },
  {
    ulid: 'event13',
    userId: eventCreatorsList[0].id,
    title: 'Glastonbury Pyramid Stage',
    content: '<h1>Glastonbury</h1><p><strong>Pyramid Stage, 28th June.</strong></p><p>Mud, sunshine and a sunset set nobody wanted to end.</p>',
    contentPlain: 'Glastonbury\nPyramid Stage, 28th June.\nMud, sunshine and a sunset set nobody wanted to end.',
    eventDate: new Date(2026, 5, 28),
    rating: 'great',
    authorName: eventCreatorsList[0].fullName,
    eventTypes: [eventTypesList[1]],
    createdAt: new Date(2026, 6, 1),
    updatedAt: new Date(2026, 6, 5),
  },
  {
    ulid: 'event14',
    userId: eventCreatorsList[3].id,
    title: 'London Marathon Finish Line',
    content: '<h2>London Marathon</h2><ul><li>40,000 runners</li><li>Millions raised for charity</li><li>One emotional final mile past Buckingham Palace</li></ul>',
    contentPlain: 'London Marathon\n- 40,000 runners\n- Millions raised for charity\n- One emotional final mile past Buckingham Palace',
    eventDate: new Date(2026, 3, 26),
    rating: 'great',
    authorName: eventCreatorsList[3].fullName,
    eventTypes: [eventTypesList[2]],
    createdAt: new Date(2026, 3, 27),
    updatedAt: new Date(2026, 4, 1),
  },
  {
    ulid: 'event15',
    userId: eventCreatorsList[1].id,
    title: 'Coldplay - Music of the Spheres',
    content: '<h1>Coldplay - Music of the Spheres</h1><p>Wembley Stadium, 12th November.</p><ul><li>Neon wristbands</li><li>Confetti cannons</li><li>Two encores</li></ul>',
    contentPlain: 'Coldplay - Music of the Spheres\nWembley Stadium, 12th November.\n- Neon wristbands\n- Confetti cannons\n- Two encores',
    eventDate: new Date(2026, 10, 12),
    rating: 'great',
    authorName: eventCreatorsList[1].fullName,
    eventTypes: [eventTypesList[0]],
    createdAt: new Date(2026, 4, 28),
    updatedAt: new Date(2026, 5, 16),
  },
  {
    ulid: 'event16',
    userId: eventCreatorsList[0].id,
    title: 'G7 Summit in Cornwall',
    content: '<h1>G7 Summit</h1><ol><li>Leaders met behind closed doors</li><li>Questions on climate and trade</li><li>Security was immense</li></ol>',
    contentPlain: 'G7 Summit\n1. Leaders met behind closed doors\n2. Questions on climate and trade\n3. Security was immense',
    eventDate: new Date(2026, 7, 14),
    rating: 'neutral',
    authorName: eventCreatorsList[0].fullName,
    eventTypes: [eventTypesList[3]],
    createdAt: new Date(2026, 7, 15),
    updatedAt: new Date(2026, 7, 16),
  },
  {
    ulid: 'event17',
    userId: eventCreatorsList[2].id,
    title: 'Annual Sales Kickoff',
    content: '<h1>Annual Sales Kickoff</h1><p><strong>ExCeL, 19th January.</strong></p><p>Three thousand colleagues and one giant stage.</p><p>A keynote promising the biggest product year yet.</p>',
    contentPlain: 'Annual Sales Kickoff\nExCeL, 19th January.\nThree thousand colleagues and one giant stage.\nA keynote promising the biggest product year yet.',
    eventDate: new Date(2026, 0, 19),
    rating: 'good',
    authorName: eventCreatorsList[2].fullName,
    eventTypes: [eventTypesList[4]],
    createdAt: new Date(2026, 0, 20),
    updatedAt: new Date(2026, 0, 22),
  },
  {
    ulid: 'event18',
    userId: eventCreatorsList[1].id,
    title: 'Edinburgh Fringe Opening Weekend',
    content: '<h2>Edinburgh Fringe Opening Weekend</h2><ol><li>Street performers on the Royal Mile</li><li>Pop up stages in every square</li><li>Flyers, flyers and more flyers</li></ol>',
    contentPlain: 'Edinburgh Fringe Opening Weekend\n1. Street performers on the Royal Mile\n2. Pop up stages in every square\n3. Flyers, flyers and more flyers',
    eventDate: new Date(2026, 7, 2),
    rating: 'good',
    authorName: eventCreatorsList[1].fullName,
    eventTypes: [eventTypesList[1]],
    createdAt: new Date(2026, 6, 28),
    updatedAt: new Date(2026, 7, 3),
  },
  {
    ulid: 'event19',
    userId: eventCreatorsList[4].id,
    title: 'Six Nations Decider at Twickenham',
    content: '<p><strong>Six Nations decider at Twickenham.</strong> The title came down to the final kick of the tournament.</p>',
    contentPlain: 'Six Nations decider at Twickenham. The title came down to the final kick of the tournament.',
    eventDate: new Date(2026, 2, 14),
    rating: 'good',
    authorName: eventCreatorsList[4].fullName,
    eventTypes: [eventTypesList[2]],
    createdAt: new Date(2026, 2, 15),
    updatedAt: new Date(2026, 2, 16),
  },
  {
    ulid: 'event20',
    userId: eventCreatorsList[3].id,
    title: 'The Rolling Stones - Hackney Diamonds',
    content: '<h1>Hackney Diamonds</h1><p>Hyde Park, a warm October evening, and Satisfaction ringing out across the grass.</p>',
    contentPlain: 'Hackney Diamonds\nHyde Park, a warm October evening, and Satisfaction ringing out across the grass.',
    eventDate: new Date(2026, 9, 8),
    rating: 'good',
    authorName: eventCreatorsList[3].fullName,
    eventTypes: [eventTypesList[0]],
    createdAt: new Date(2026, 3, 12),
    updatedAt: new Date(2026, 4, 2),
  },
  {
    ulid: 'event21',
    userId: eventCreatorsList[0].id,
    title: 'AI in Enterprise Roundtable',
    content: '<p>Chief technology officers traded notes on adoption and risk over a working breakfast at the Shard.</p>',
    contentPlain: 'Chief technology officers traded notes on adoption and risk over a working breakfast at the Shard.',
    eventDate: new Date(2026, 10, 3),
    rating: 'neutral',
    authorName: eventCreatorsList[0].fullName,
    eventTypes: [eventTypesList[4]],
    createdAt: new Date(2026, 10, 4),
    updatedAt: new Date(2026, 10, 6),
  },
  {
    ulid: 'event22',
    userId: eventCreatorsList[4].id,
    title: 'Hay Festival Literature Weekend',
    content: '<p>Hay-on-Wye: a town of bookshops, filled for one weekend with authors, poets and thinkers.</p>',
    contentPlain: 'Hay-on-Wye: a town of bookshops, filled for one weekend with authors, poets and thinkers.',
    eventDate: new Date(2026, 4, 24),
    rating: 'neutral',
    authorName: eventCreatorsList[4].fullName,
    eventTypes: [eventTypesList[1]],
    createdAt: new Date(2026, 4, 15),
    updatedAt: new Date(2026, 4, 26),
  },
  {
    ulid: 'event23',
    userId: eventCreatorsList[1].id,
    title: 'FA Cup Final at Wembley',
    content: '<h1>FA Cup Final</h1><p>Wembley, 16th May. A last minute winner sent the supporters behind the goal into raptures.</p>',
    contentPlain: 'FA Cup Final\nWembley, 16th May.  A last minute winner sent the supporters behind the goal into raptures.',
    eventDate: new Date(2026, 4, 16),
    rating: 'good',
    authorName: eventCreatorsList[1].fullName,
    eventTypes: [eventTypesList[2]],
    createdAt: new Date(2026, 4, 17),
    updatedAt: new Date(2026, 4, 18),
  },
  {
    ulid: 'event24',
    userId: eventCreatorsList[0].id,
    title: 'Radiohead at the Roundhouse',
    content: '<h1>Radiohead at the Roundhouse</h1><p><em>“An intimate, hypnotic set bathed in blue light.”</em></p><p>They opened with Daydreaming and never let go of the room.</p>',
    contentPlain: 'Radiohead at the Roundhouse\n"An intimate, hypnotic set bathed in blue light."\nThey opened with Daydreaming and never let go of the room.',
    eventDate: new Date(2026, 8, 22),
    rating: 'good',
    authorName: eventCreatorsList[0].fullName,
    eventTypes: [eventTypesList[0]],
    createdAt: new Date(2026, 4, 30),
    updatedAt: new Date(2026, 5, 18),
  },
  {
    ulid: 'event25',
    userId: eventCreatorsList[3].id,
    title: 'Local Election Results Night',
    content: '<p>A long night of recounts in Manchester as the council changed hands for the first time in a decade.</p>',
    contentPlain: 'A long night of recounts in Manchester as the council changed hands for the first time in a decade.',
    eventDate: new Date(2026, 4, 7),
    rating: 'neutral',
    authorName: eventCreatorsList[3].fullName,
    eventTypes: [eventTypesList[3]],
    createdAt: new Date(2026, 4, 8),
    updatedAt: new Date(2026, 4, 9),
  },
  {
    ulid: 'event26',
    userId: eventCreatorsList[1].id,
    title: 'Party Conference Keynote',
    content: '<h1>Party Conference Keynote</h1><p>Brighton, 29th September.</p><ul><li>Packed main hall</li><li>Two standing ovations</li><li>A vision for the year ahead</li></ul>',
    contentPlain: 'Party Conference Keynote\nBrighton, 29th September.\n- Packed main hall\n- Two standing ovations\n- A vision for the year ahead',
    eventDate: new Date(2026, 8, 29),
    rating: 'neutral',
    authorName: eventCreatorsList[1].fullName,
    eventTypes: [eventTypesList[3]],
    createdAt: new Date(2026, 8, 30),
    updatedAt: new Date(2026, 9, 1),
  },
]
